apiVersion: v1
data:
  mongodb-password: ""
  mongodb-root-password: ""
kind: Secret
metadata:
  labels:
    app: mongodb-mongodb
    release: mongodb
  name: mongodb-mongodb
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-mongodb
    release: mongodb
  name: mongodb-mongodb
spec:
  ports:
  - name: mongodb
    port: 27017
    targetPort: mongodb
  selector:
    app: mongodb-mongodb
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mongodb-mongodb
    release: mongodb
  name: mongodb-mongodb
spec:
  template:
    metadata:
      labels:
        app: mongodb-mongodb
    spec:
      containers:
      - env:
        - name: MONGODB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mongodb-root-password
              name: mongodb-mongodb
        - name: MONGODB_USERNAME
          value: ""
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mongodb-password
              name: mongodb-mongodb
        - name: MONGODB_DATABASE
          value: ""
        image: bitnami/mongodb:3.4.3-r0
        imagePullPolicy: ""
        livenessProbe:
          exec:
            command:
            - mongo
            - --eval
            - db.adminCommand('ping')
          initialDelaySeconds: 30
          timeoutSeconds: 5
        name: mongodb-mongodb
        ports:
        - containerPort: 27017
          name: mongodb
        readinessProbe:
          exec:
            command:
            - mongo
            - --eval
            - db.adminCommand('ping')
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - mountPath: /bitnami/mongodb
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mongodb-mongodb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
  name: mongodb-mongodb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
