apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
spec:
  template:
    spec:
      containers:
      - name: mongodb
        volumeMounts:
        - mountPath: /bitnami/mongodb
          name: data
      volumes:
      - name: data
        awsElasticBlockStore:
          volumeID: $(MONGODB_DATA_VOLUME_EBS)
          fsType: ext4
      nodeSelector:
        failure-domain.beta.kubernetes.io/zone: $(MONGODB_NODE_ZONE)
