bases:
- ../../base

patchesStrategicMerge:
- ebs-data-volume.yaml

configMapGenerator:
- name: mongodb
  literals:
  # This AWS EBS volume must already exist, e.g. vol-0a67a5afead0ae81c
  - MONGODB_DATA_VOLUME_EBS=
  # Availability zone of the AWS EBS volume, e.g. us-west-1b
  - MONGODB_NODE_ZONE=

vars:
- name: MONGODB_DATA_VOLUME_EBS
  objref:
    kind: ConfigMap
    name: mongodb
    apiVersion: v1
  fieldref:
    fieldpath: data.MONGODB_DATA_VOLUME_EBS
- name: MONGODB_NODE_ZONE
  objref:
    kind: ConfigMap
    name: mongodb
    apiVersion: v1
  fieldref:
    fieldpath: data.MONGODB_NODE_ZONE

configurations:
- kustomizeconfig.yaml
