apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
  name: mongodb-mongodb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
