apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
    release: mongodb
  name: mongodb
spec:
  ports:
  - name: mongodb
    port: 27017
    targetPort: mongodb
  selector:
    app: mongodb
    release: mongodb
  type: ClusterIP
